# Generated by Django 5.2.4 on 2025-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_alter_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='fullname',
        ),
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.CharField(default='80100', max_length=255),
        ),
        migrations.AddField(
            model_name='admin',
            name='city',
            field=models.CharField(default='Mombasa', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='country',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='firstName',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='lastName',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='mobileno',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobileno',
            field=models.CharField(max_length=20),
        ),
    ]
