# Generated by Django 5.2.4 on 2025-09-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_remove_admin_fullname_admin_address_admin_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
